### ISSUE TITLE
random.choice() may not be cryptographically secured

### ISSUE THREAD

**Issue by kgrsajid** [ramuta/IOTA-seed-generator#1]
So I guess, it's best to avoid this method to generate IOTA seed.

**Comment by ramuta** [comment]
Yes, I agree it lacks sufficient entropy. Any idea how to add it and still keep things simple?

**Comment by kgrsajid** [comment]
I don't work with Python much. But you can take a look at this thread - [https://stackoverflow.com/questions/20936993/how-can-i-create-a-random-number-that-is-cryptographically-secure-in-python](url)

I think you have any of the following options to make it cryptographically secured:
[https://paragonie.com/blog/2016/05/how-generate-secure-random-numbers-in-various-programming-languages#python-csprng](url) 
[https://www.dlitz.net/software/pycrypto/api/current/Crypto.Random.random-module.html](url)

Cheers.

**Comment by ramuta** [comment]
Thanks. As I see, `choice()` from the `secrets` module in Python 3 is a preferred option and cryptographically secure: https://docs.python.org/3.6/library/secrets.html.

I'll probably use this one and replace `random`.

**Comment by kgrsajid** [comment]
It says in the doc, 

> In particularly, secrets should be used in preference to the default **pseudo-random number** generator in the random module, which is designed for modelling and simulation, **not security or cryptography**.

So I wouldn't use it either. The safest to use would be StrongRandom or os.urandom.

**Comment by ramuta** [comment]
The `random` module "is designed for modelling and simulation, not security or cryptography". The `secrets` module **is** secure (at least as long 256 bits of randomness is sufficient).

**Comment by kgrsajid** [comment]
Yes, okay. `SystemRandom` is under `secrets`. So it would work.
